title: Rotaract Koramangala
description: Rotaract Club Koramangala in Bangalore is a community based club of youngsters (18 to 30 years of age).We organize and participate in projects with an aim to create a change in the society.

include:
  - _pages

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap